services:
  - type: web
    name: bank-dannyh-odarennosti
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.7
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_PATH
        value: /var/data/achievements.db
      - key: UPLOAD_FOLDER
        value: /var/data/uploads
    disk:
      name: app-data
      mountPath: /var/data
      sizeGB: 1
